
[functions.analizar-ndvi]
enabled = true
verify_jwt = true
import_map = "./functions/analizar-ndvi/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analizar-ndvi/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analizar-ndvi/*.html" ]

[functions.delete-polygon-agromonitoring]
enabled = true
verify_jwt = true
import_map = "./functions/delete-polygon-agromonitoring/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-polygon-agromonitoring/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-polygon-agromonitoring/*.html" ]

[functions.generar-snapshot-potrero]
enabled = true
verify_jwt = true
import_map = "./functions/generar-snapshot-potrero/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generar-snapshot-potrero/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generar-snapshot-potrero/*.html" ]
